#!/command/with-contenv sh
cd /rails

export DB_HOST=127.0.0.1
export DB_PORT=5432
export POSTGRES_USER=sure_user
export POSTGRES_PASSWORD=internal_sure_pass
export POSTGRES_DB=sure_production
export REDIS_URL=redis://127.0.0.1:6379/1

# Launch Background Worker
exec bundle exec sidekiq